/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ./Bulb.glb --transform 
Files: ./Bulb.glb [284.53KB] > /Users/dialectic/repositories/thecocoonstudio/izzy/web/public/models/Bulb-transformed.glb [36.15KB] (87%)
Author: Fishboe (https://sketchfab.com/ministephen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/edison-light-bulb-aeb0e4832f04463280510e550e2cdbd5
Title: Edison Light Bulb
*/

import { MeshTransmissionMaterial, useGLTF } from '@react-three/drei'

import Model from 'public/models/Bulb-transformed.glb'
import { Color } from 'three'

import { useFrame } from '@react-three/fiber'
import { forwardRef } from 'react'

const Bulb = forwardRef(function Bulb(props, ref) {
  const { nodes, materials } = useGLTF(Model)

  materials.PaletteMaterial002.opacity = 0.4

  materials.PaletteMaterial004.toneMapped = false
  materials.PaletteMaterial004.color = new Color('orange')
  materials.PaletteMaterial004.emissive = materials.PaletteMaterial004.color
  materials.PaletteMaterial004.emissiveIntensity = 3

  useFrame((state) => {
    materials.PaletteMaterial004.emissiveIntensity =
      3 + Math.sin(1.5 * state.clock.elapsedTime)
  })

  return (
    <group ref={ref} {...props}>
      <mesh
        castShadow
        geometry={nodes.Object_2.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        geometry={nodes.Object_3.geometry}
        /* material={materials.PaletteMaterial002} */
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <MeshTransmissionMaterial
          transmission={1.1}
          attach='material'
          samples={6}
          /* backside */
          thickness={1.7}
          /* backsideThickness={0.001} */
          chromaticAberration={0.03}
          anisotropy={0.02}
          distortion={0.01}
          distortionScale={0.05}
          iridescence={1}
          iridescenceIOR={1}
          iridescenceThicknessRange={[0, 1400]}
        />
      </mesh>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial003}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials.PaletteMaterial004}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
})

useGLTF.preload('/models/Bulb-transformed.glb')

export default Bulb
