/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Metazeon (https://sketchfab.com/Metazeon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sony-a7m4-with-gm1635-f28-93fb2cac30e741f580faf022795f7d50
Title: SONY A7M4 with GM1635 f2.8
*/

import { useGLTF } from '@react-three/drei'
import Model from 'website/assets/camera/camera.glb'

export function Camera(props) {
  const { nodes, materials } = useGLTF(Model)
  return (
    <group
      {...props}
      scale={0.005}
      rotation={[0, Math.PI * 1.33, 0]}
      position={[0.8, 0.75, -0.3]} /* dispose={null} */
    >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.SONY_A7M4_GM1635_RC_LOD0_u0_v0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.SONY_A7M4_GM1635_RC_LOD0_u0_v0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.SONY_A7M4_GM1635_RC_LOD0_u0_v0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.SONY_A7M4_GM1635_RC_LOD0_u0_v0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.SONY_A7M4_GM1635_RC_LOD0_u0_v0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.SONY_A7M4_GM1635_RC_LOD0_u0_v0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.SONY_A7M4_GM1635_RC_LOD0_u0_v0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.SONY_A7M4_GM1635_RC_LOD0_u0_v0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.SONY_A7M4_GM1635_RC_LOD0_u0_v0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials.SONY_A7M4_GM1635_RC_LOD0_u0_v0}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.SONY_A7M4_GM1635_RC_LOD0_u0_v0}
        />
      </group>
    </group>
  )
}

useGLTF.preload(Model)
