/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Keandir (https://sketchfab.com/Keandir)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/photorealistic-western-guitar-f8d68a2c328345418db71b36f44168b9
Title: Photorealistic (Western) Guitar
*/

import { useGLTF } from '@react-three/drei'
import Model from 'website/assets/guitar/guitar.glb'

export function Guitar(props) {
  const { nodes, materials } = useGLTF(Model)
  return (
    <group
      {...props}
      position={[1.2, 0.39, 0.3]}
      scale={0.3}
      rotation-x={Math.PI / 2 + -0.4} /* dispose={null} */
    >
      <group position={[0.009, 0.009, 0.076]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.SIDE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials.back}
        />
      </group>
      <group position={[0.009, 0.014, 0.664]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials.white}
        />
      </group>
      <group position={[0.005, -0.053, -0.664]} rotation={[0.016, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials.neck}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials.SIDE}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_15.geometry}
          material={materials.white}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.strings}
        position={[-0.009, 0.053, 0.586]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials.metal}
        position={[0.005, -0.05, -0.664]}
        rotation={[0.016, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload(Model)
