/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 /Users/dialectic/Downloads/instagram.glb --transform 
Files: /Users/dialectic/Downloads/instagram.glb [1.65MB] > /Users/dialectic/repositories/thecocoonstudio/izzy/instagram-transformed.glb [39.33KB] (98%)
Author: studiometa (https://sketchfab.com/studiometa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/instagram-3d-1da8f8c3e84f4a9ca445d5d3538a998e
Title: Instagram 3d
*/

import Model from 'public/models/instagram.glb'
import { useGLTF } from '@react-three/drei'
import {
  forwardRef,
  useRef,
  useImperativeHandle,
  useMemo,
  useEffect,
} from 'react'

export const Instagram = forwardRef(function Instagram(
  { colorTheme, ...props },
  ref,
) {
  const { nodes } = useGLTF(Model)
  const geometry = useMemo(
    () => nodes['Objeto_2_Tinta_(3)_0'].geometry,
    [nodes],
  )
  const group = useRef()
  useImperativeHandle(ref, () => group.current)

  useEffect(() => {
    const { min, max } = geometry.boundingBox
    const factor = 0.7 / (Math.abs(max.x) + Math.abs(min.x))
    geometry.center()
    geometry.scale(factor, factor, factor)

    return () => {
      geometry?.dispose()
    }
  }, [geometry])
  return (
    <group ref={group} {...props}>
      <mesh geometry={geometry} position-z={0.05}>
        <meshStandardMaterial
          roughness={0.2}
          metalness={0.4}
          color={colorTheme.white}
          opacity={0.8}
          transparent
        />
      </mesh>
    </group>
  )
})
// useGLTF.preload(Model)
